# Generated by Django 5.1.2 on 2024-11-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=100)),
                ('attribute_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('result', models.TextField()),
            ],
        ),
    ]
